// Safe demo content only. All records are drafts or inactive so they stay out
// of the public API until an event manager reviews and publishes them.
const demoNoteAr = "بيانات تجريبية للتجربة فقط — راجعها وعدّلها قبل النشر.";
const demoNoteEn = "Demo content for testing only. Review and edit before publishing.";

module.exports = {
  projectCategories: [
    { name_ar: "مشاريع الاختراع (تجريبي)", name_en: "Demo Invention Projects", is_active: false },
    { name_ar: "مشاريع الدفاع (تجريبي)", name_en: "Demo Defense Projects", is_active: false },
  ],
  competitions: [
    {
      name_ar: "مسابقة الروبوتات الجامعية (تجريبي)",
      name_en: "University Robotics Competition (Demo)",
      description_ar: demoNoteAr,
      description_en: demoNoteEn,
      category_code: "sensing",
      requirements_ar: "تُضاف المتطلبات الرسمية بعد اعتمادها.",
      requirements_en: "Official requirements to be added after approval.",
      audience_type: "طلاب وطالبات الجامعات",
      registration_status: "coming_soon",
      status: "draft",
      is_featured: false,
    },
    {
      name_ar: "مسابقة الثانوي والمبتدئين (تجريبي)",
      name_en: "Secondary and Beginners Competition (Demo)",
      description_ar: demoNoteAr,
      description_en: demoNoteEn,
      category_code: "simulation",
      requirements_ar: "تُضاف المتطلبات الرسمية بعد اعتمادها.",
      requirements_en: "Official requirements to be added after approval.",
      audience_type: "طلاب وطالبات المرحلة الثانوية",
      registration_status: "coming_soon",
      status: "draft",
      is_featured: false,
    },
    {
      name_ar: "تحدي كانسات والصواريخ (تجريبي)",
      name_en: "CanSat and Rockets Challenge (Demo)",
      description_ar: demoNoteAr,
      description_en: demoNoteEn,
      category_code: "simulation",
      requirements_ar: "تُضاف المتطلبات الرسمية بعد اعتمادها.",
      requirements_en: "Official requirements to be added after approval.",
      audience_type: "طلاب وطالبات الجامعات",
      registration_status: "coming_soon",
      status: "draft",
      is_featured: false,
    },
    {
      name_ar: "تحدي الروبوتات القتالية (تجريبي)",
      name_en: "Combat Robotics Challenge (Demo)",
      description_ar: demoNoteAr,
      description_en: demoNoteEn,
      category_code: "combat",
      requirements_ar: "تُضاف المتطلبات الرسمية بعد اعتمادها.",
      requirements_en: "Official requirements to be added after approval.",
      audience_type: "يُحدَّد لاحقًا",
      registration_status: "coming_soon",
      status: "draft",
      is_featured: false,
    },
  ],
  workshops: [
    {
      title_ar: "أساسيات الروبوتات (تجريبي)",
      title_en: "Robotics Fundamentals (Demo)",
      description_ar: demoNoteAr,
      description_en: demoNoteEn,
      start_at: "2030-01-01T10:00:00+03:00",
      registration_status: "coming_soon",
      status: "draft",
      is_featured: false,
    },
    {
      title_ar: "برمجة المتحكمات الدقيقة (تجريبي)",
      title_en: "Microcontroller Programming (Demo)",
      description_ar: demoNoteAr,
      description_en: demoNoteEn,
      start_at: "2030-01-02T10:00:00+03:00",
      registration_status: "coming_soon",
      status: "draft",
      is_featured: false,
    },
    {
      title_ar: "تصميم الدوائر الإلكترونية (تجريبي)",
      title_en: "Electronic Circuit Design (Demo)",
      description_ar: demoNoteAr,
      description_en: demoNoteEn,
      start_at: "2030-01-03T10:00:00+03:00",
      registration_status: "coming_soon",
      status: "draft",
      is_featured: false,
    },
    {
      title_ar: "الذكاء الاصطناعي في الروبوتات (تجريبي)",
      title_en: "AI in Robotics (Demo)",
      description_ar: demoNoteAr,
      description_en: demoNoteEn,
      start_at: "2030-01-04T10:00:00+03:00",
      registration_status: "coming_soon",
      status: "draft",
      is_featured: false,
    },
    {
      title_ar: "المستشعرات وتطبيقاتها (تجريبي)",
      title_en: "Sensors and Their Applications (Demo)",
      description_ar: demoNoteAr,
      description_en: demoNoteEn,
      start_at: "2030-01-05T10:00:00+03:00",
      registration_status: "coming_soon",
      status: "draft",
      is_featured: false,
    },
  ],
  projects: [
    {
      name_ar: "روبوت فرز ذكي (تجريبي)",
      name_en: "Smart Sorting Robot (Demo)",
      description_ar: demoNoteAr,
      description_en: demoNoteEn,
      project_type: "invention",
      category_name_en: "Demo Invention Projects",
      team_name: "فريق تجريبي — RoboTactic",
      stage_ar: "مسودة تجريبية",
      stage_en: "Demo draft",
      status: "draft",
      is_featured: false,
    },
    {
      name_ar: "روبوت استكشاف ميداني (تجريبي)",
      name_en: "Field Exploration Robot (Demo)",
      description_ar: demoNoteAr,
      description_en: demoNoteEn,
      project_type: "defense",
      category_name_en: "Demo Defense Projects",
      team_name: "فريق تجريبي — RoboTactic",
      stage_ar: "مسودة تجريبية",
      stage_en: "Demo draft",
      status: "draft",
      is_featured: false,
    },
    {
      name_ar: "عربة روبوتية لتجنّب العوائق (تجريبي)",
      name_en: "Obstacle Avoidance Rover (Demo)",
      description_ar: demoNoteAr,
      description_en: demoNoteEn,
      project_type: "invention",
      category_name_en: "Demo Invention Projects",
      team_name: "فريق تجريبي — RoboTactic",
      stage_ar: "مسودة تجريبية",
      stage_en: "Demo draft",
      status: "draft",
      is_featured: false,
    },
  ],
  announcements: [
    {
      title_ar: "إعلان تجريبي",
      title_en: "Demo Announcement",
      description_ar: demoNoteAr,
      description_en: demoNoteEn,
      status: "draft",
    },
    {
      title_ar: "فتح التسجيل قريبًا (تجريبي)",
      title_en: "Registration Opening Soon (Demo)",
      description_ar: demoNoteAr,
      description_en: demoNoteEn,
      status: "draft",
    },
    {
      title_ar: "تحديث برنامج الورش (تجريبي)",
      title_en: "Workshop Program Update (Demo)",
      description_ar: demoNoteAr,
      description_en: demoNoteEn,
      status: "draft",
    },
  ],
  timelineEvents: [
    {
      title_ar: "فعالية تجريبية",
      title_en: "Demo Event",
      description_ar: demoNoteAr,
      description_en: demoNoteEn,
      start_at: "2030-01-01T09:00:00+03:00",
      end_at: "2030-01-01T10:00:00+03:00",
      location_ar: "يُحدَّد لاحقًا",
      location_en: "To be announced",
      status: "draft",
    },
    {
      title_ar: "استقبال الفرق (تجريبي)",
      title_en: "Team Check-in (Demo)",
      description_ar: demoNoteAr,
      description_en: demoNoteEn,
      start_at: "2030-01-01T08:00:00+03:00",
      end_at: "2030-01-01T09:00:00+03:00",
      location_ar: "يُحدَّد لاحقًا",
      location_en: "To be announced",
      status: "draft",
    },
    {
      title_ar: "ختام الملتقى (تجريبي)",
      title_en: "Event Closing (Demo)",
      description_ar: demoNoteAr,
      description_en: demoNoteEn,
      start_at: "2030-01-01T16:00:00+03:00",
      end_at: "2030-01-01T17:00:00+03:00",
      location_ar: "يُحدَّد لاحقًا",
      location_en: "To be announced",
      status: "draft",
    },
  ],
  faqs: [
    {
      question_ar: "هل هذه بيانات الملتقى الرسمية؟",
      question_en: "Is this official event information?",
      answer_ar: "لا، هذا سجل تجريبي للتطوير ويجب تعديله قبل النشر.",
      answer_en: "No. This is a development demo record and must be reviewed before publishing.",
      display_order: 1,
      is_active: false,
    },
    {
      question_ar: "كيف يتم التسجيل في المسابقات؟",
      question_en: "How do I register for competitions?",
      answer_ar: "تُضاف روابط التسجيل الرسمية بعد اعتمادها.",
      answer_en: "Official registration links will be added after approval.",
      display_order: 2,
      is_active: false,
    },
    {
      question_ar: "هل أحتاج إلى حساب في الموقع؟",
      question_en: "Do I need an account on the website?",
      answer_ar: "تُحدَّد آلية المشاركة في التعليمات الرسمية للملتقى.",
      answer_en: "Participation details will be provided in the official event instructions.",
      display_order: 3,
      is_active: false,
    },
    {
      question_ar: "أين أجد مواعيد الورش؟",
      question_en: "Where can I find workshop times?",
      answer_ar: "ستُنشر المواعيد المعتمدة في صفحة ورش العمل.",
      answer_en: "Approved times will be published on the Workshops page.",
      display_order: 4,
      is_active: false,
    },
    {
      question_ar: "كيف أعرف أن المحتوى تجريبي؟",
      question_en: "How can I tell demo content apart?",
      answer_ar: "تظهر كلمة (تجريبي) في السجل التجريبي.",
      answer_en: "Demo records are marked with (Demo) in their labels.",
      display_order: 5,
      is_active: false,
    },
  ],
  siteSettings: {
    id: 1,
    event_start_at: "2030-01-01T09:00:00+03:00",
    event_end_at: "2030-01-01T17:00:00+03:00",
    event_location_ar: "موقع تجريبي — يُستبدل بالموقع المعتمد",
    event_location_en: "Demo venue — replace with the approved location",
    general_registration_url: "https://example.invalid/register",
    official_email: "events@example.invalid",
  },
  adminUsers: [
    { full_name: "مدير عام تجريبي", email: "super.admin.demo@example.invalid", role_code: "super_admin", phone: null, is_active: false },
    { full_name: "مدير مسابقات تجريبي", email: "competition.manager.demo@example.invalid", role_code: "competition_manager", phone: null, is_active: false },
    { full_name: "مدير ورش تجريبي", email: "workshop.manager.demo@example.invalid", role_code: "workshop_manager", phone: null, is_active: false },
  ],
  teams: [
    {
      competition_name_en: "University Robotics Competition (Demo)",
      team_name: "فريق تجريبي 01",
      team_leader_name: "قائد تجريبي 01",
      leader_email: "demo.team01@example.invalid",
      leader_phone: "0000000000",
      member_names: "عضو تجريبي 01-أ، عضو تجريبي 01-ب",
    },
    {
      competition_name_en: "University Robotics Competition (Demo)",
      team_name: "فريق تجريبي 02",
      team_leader_name: "قائد تجريبي 02",
      leader_email: "demo.team02@example.invalid",
      leader_phone: "0000000000",
      member_names: "عضو تجريبي 02-أ، عضو تجريبي 02-ب، عضو تجريبي 02-ج",
    },
    {
      competition_name_en: "Secondary and Beginners Competition (Demo)",
      team_name: "فريق المبتدئين التجريبي",
      team_leader_name: "قائد تجريبي 03",
      leader_email: "demo.team03@example.invalid",
      leader_phone: "0000000000",
      member_names: "عضو تجريبي 03-أ، عضو تجريبي 03-ب",
    },
  ],
  speakers: [
    { full_name: "متحدث تجريبي 01", phone: "0000000000", notes: "بيانات اصطناعية للتطوير فقط.", workshops: ["Robotics Fundamentals (Demo)", "Microcontroller Programming (Demo)"] },
    { full_name: "متحدث تجريبي 02", phone: "0000000000", notes: "بيانات اصطناعية للتطوير فقط.", workshops: ["Electronic Circuit Design (Demo)"] },
  ],
  projectMembers: [
    { project_name_en: "Smart Sorting Robot (Demo)", name: "عضو مشروع تجريبي 01", display_order: 1 },
    { project_name_en: "Smart Sorting Robot (Demo)", name: "عضو مشروع تجريبي 02", display_order: 2 },
    { project_name_en: "Field Exploration Robot (Demo)", name: "عضو مشروع تجريبي 03", display_order: 1 },
    { project_name_en: "Obstacle Avoidance Rover (Demo)", name: "عضو مشروع تجريبي 04", display_order: 1 },
  ],
  sponsors: [
    { name: "راعي تجريبي 01", description_ar: "بيانات تجريبية فقط.", description_en: "Demo data only.", logo_url: "/logo/robotactic-mark-white.png", sponsor_type: "sponsor", level: "تجريبي", website_url: null, display_order: 1, is_active: false },
    { name: "شريك تجريبي 01", description_ar: "بيانات تجريبية فقط.", description_en: "Demo data only.", logo_url: "/logo/robotactic-mark-white.png", sponsor_type: "partner", level: "تجريبي", website_url: null, display_order: 2, is_active: false },
  ],
  contactMessages: [
    { name: "مرسل تجريبي 01", email: "demo.sender01@example.invalid", subject: "استفسار تجريبي", message: "هذه رسالة اصطناعية لا تمثل استفسارًا حقيقيًا.", status: "unread" },
    { name: "مرسل تجريبي 02", email: "demo.sender02@example.invalid", subject: "رسالة تجريبية تمت قراءتها", message: "هذه رسالة اصطناعية لا تمثل استفسارًا حقيقيًا.", status: "read" },
    { name: "مرسل تجريبي 03", email: "demo.sender03@example.invalid", subject: "رسالة تجريبية محلولة", message: "هذه رسالة اصطناعية لا تمثل استفسارًا حقيقيًا.", status: "resolved" },
  ],
};
